[package]
name = "adventofcode2022"
version = "0.1.0"
edition = "2021"

[lib]
name = "utils"
path = "src/utils/utils.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sscanf = "0.4.0"
itertools = "0.7.8"
